# Generated by Django 3.1.7 on 2021-03-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0002_read_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='Attachments')),
            ],
        ),
    ]
